class LocalAdapter:

    def generate(self, tenant_id, domain, message, memory_context):

        message_lower = message.lower()


        # STEP 1: RECALL ANY FAVORITE FACT
        if "what is my favorite" in message_lower:

            keyword = message_lower.replace("what is my favorite", "").strip().replace("?", "")

            for line in memory_context.split("\n"):

                if f"favorite {keyword}" in line.lower():

                    clean = line.replace("Aura:", "").strip()

                    if clean:
                        return clean


        # STEP 2: LEARN ANY FAVORITE FACT
        if "my favorite" in message_lower and "is" in message_lower:

            return f"I will remember that {message_lower}."


        # STEP 3: DEFAULT RESPONSE
        return (
            f"🧠 Aura Local Intelligence\n\n"
            f"Tenant: {tenant_id}\n"
            f"Domain: {domain}\n\n"
            f"User Message:\n{message}\n\n"
            f"Response generated by Aura Local Intelligence."
        )
