class OpenAIAdapter:

    def generate(
        self,
        tenant_id: str,
        domain: str,
        message: str,
        memory_context: str
    ):
        """
        Cloud intelligence (fallback simulated)
        """

        response = (
            "☁️ Aura Cloud Intelligence\n\n"
            f"Tenant: {tenant_id}\n"
            f"Domain: {domain}\n\n"
            f"{memory_context}\n"
            f"User Message:\n{message}\n\n"
            "Response generated by Aura Cloud Intelligence."
        )

        return response
